# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: marcus.wittig@fh-zwickau.de
author_name: Marcus Wittig
has_binder: false
has_settings: true
kind: server
labextension_name: kore-extension
project_short_description: A JupyterLab extension to expand the eponymous service
    for course management and grade handling between LMS and JupyterHub via LTI 1.3.
python_name: kore_extension
repository: ''
test: true

